#!/bin/bash
# letsencrypt was installed (and can be updated) by running:
#     sudo -H VENV_PATH=/usr/local/letsencrypt ./letsencrypt-auto --help
# in a copy of the GitHub repository.

# Editing this list and rerunning the script should be sufficient to add a new
# domain (as of 2016-01-09, wildcard certs are still not supported):
DOMAINS=varonathe.org,www.varonathe.org,mail.varonathe.org

VENV_PATH=/usr/local/letsencrypt

set -e
if [ "$1" = "--force" -o \
     -n "$(find /etc/letsencrypt/live/*/cert.pem -mtime 60 -print)" ]
then service apache2 stop
     $VENV_PATH/bin/letsencrypt certonly \
         --standalone \
         --rsa-key-size 4096 \
         --renew-by-default \
         --server https://acme-v01.api.letsencrypt.org/directory \
         --email jwodder+letsencrypt@gmail.com \
         --domains "$DOMAINS"
     service apache2 start
     service postfix stop
     service postfix start
fi
