---
- name: Install development-related packages
  apt: name={{item}} state=present update_cache=no
  with_items:
    - build-essential
    #- libncurses5-dev
    #- libncursesw5-dev
    #- ncurses-doc
    - patch
    #- perl-doc
    - pyflakes
    - python-dev
    - python-pip
    - python-requests
    - python-six
    - python-virtualenv
    - python3-dev
    - python3-pip
    - python3-requests
    - python3-six
    - python3-virtualenv
    - tox

- name: Install Docker
  ### TODO: Convert the get.docker.io script to Ansible tasks?
  shell: 'wget -qO- https://get.docker.io | bash -'
  args:
    creates: /usr/bin/docker

- name: Add admin user to `docker` group
  user: name={{admin_user}} groups=docker append=true

- name: Determine latest release of Docker Compose
  uri:
    url: https://api.github.com/repos/docker/compose/releases/latest
    return_content: true
  register: compose_latest

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{compose_latest.json.tag_name}}/docker-compose-{{ansible_system}}-{{ansible_machine}}
    dest: /usr/local/bin/docker-compose
    mode: 0755
    force: "{{update_docker_compose}}"
