---
- password_file:
    dest: "{{jwodder_root}}/etc/logger"
    length: 32
  register: logpass

- postgresql_user:
    name: logger
    password: "{{logpass.password}}"
    encrypted: true
    role_attr_flags: NOSUPERUSER,CREATEDB,CREATEROLE,LOGIN
  become_user: postgres

- postgresql_db:
    name: logs
    owner: logger
    encoding: utf8
  become_user: postgres
