---
- name: Create logsdb config file
  template:
    src: logsdb.ini
    dest: "{{jwodder_root}}/etc/logsdb.ini"
    mode: 0644

- name: Create PostgreSQL logsdb user
  postgresql_user:
    name: "{{logsdb_user}}"
    password: "{{logsdb_password}}"
    encrypted: true
    role_attr_flags: NOSUPERUSER,NOCREATEDB,NOCREATEROLE,LOGIN
  become_user: postgres

- name: Create logs database
  postgresql_db:
    name: "{{logsdb_db}}"
    owner: "{{logsdb_user}}"
    encoding: utf8
  become_user: postgres

### TODO: Run on database (cf. <http://stackoverflow.com/a/6454469>):
# GRANT SELECT ON ALL TABLES IN SCHEMA public TO {{admin_user}};
# ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO {{admin_user}};

### TODO: Ensure all tables in database are owned by {{logsdb_user}}? (ALTER
### TABLE public.$table OWNER TO {{logsdb_user}})

- name: Install virtualenv
  # We need virtualenv installed globally if we're running as root, as we won't
  # be able to run Python code installed in the admin user's userspace
  apt:
    name: virtualenv
    state: present
    update_cache: false

- name: Install jwodder-logsdb in virtualenv
  pip:
    name: git+https://github.com/jwodder/logsdb
    state: forcereinstall
    virtualenv: "{{jwodder_root}}/venvs/logsdb"
    virtualenv_python: python3
