---
- name: Record logsdb credentials
  copy:
    dest: "{{jwodder_root}}/etc/logsdb.json"
    mode: 0644
    content: |
        {{
            {
                "database": logsdb_db,
                "username": logsdb_user,
                "password": logsdb_password,
            }|to_json
        }}

- name: Create PostgreSQL logsdb user
  postgresql_user:
    name: "{{logsdb_user}}"
    password: "{{logsdb_password}}"
    encrypted: true
    role_attr_flags: NOSUPERUSER,NOCREATEDB,NOCREATEROLE,LOGIN
  become_user: postgres

- name: Create logs database
  postgresql_db:
    name: "{{logsdb_db}}"
    owner: "{{logsdb_user}}"
    encoding: utf8
  become_user: postgres

### TODO: Run on database (cf. <http://stackoverflow.com/a/6454469>):
# GRANT SELECT ON ALL TABLES IN SCHEMA public TO {{admin_user}};
# ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO {{admin_user}};

### TODO: Ensure all tables in database are owned by {{logsdb_user}}? (ALTER
### TABLE public.$table OWNER TO {{logsdb_user}})

- name: Create jwodder_logsdb folder
  file:
    path: "{{jwodder_root}}/lib/jwodder_logsdb"
    state: directory

- name: Install jwodder_logsdb skeleton
  copy:
    src: "jwodder_logsdb/{{item}}"
    dest: "{{jwodder_root}}/lib/jwodder_logsdb/{{item}}"
    backup: true
  with_items:
    - __init__.py
    - core.py
    - requirements.txt

- name: Install virtualenv
  # We need virtualenv installed globally if we're running as root, as we won't
  # be able to run Python code installed in the admin user's userspace
  apt:
    name: virtualenv
    state: present
    update_cache: false

- name: Create jwodder_logsdb virtualenv
  pip:
    requirements: "{{jwodder_root}}/lib/jwodder_logsdb/requirements.txt"
    virtualenv: "{{jwodder_root}}/venvs/logsdb"
    virtualenv_python: python3
