---
- name: Install bin/apache_access
  copy:
    src: bin/apache_access
    dest: "{{jwodder_root}}/bin/apache_access"
    mode: 0755
  notify:
    - Restart Apache

- name: Ensure apache_access errfile exists
  file:
    dest: "{{jwodder_root}}/logs/apache_access.err"
    state: touch
