---
- name: Install Apache
  apt:
    name:
        - apache2
        #- apache2-utils  # htpasswd
        #- libapache2-mod-wsgi-py3
    state: present
    update_cache: false

- name: Allow incoming HTTP(S) connections
  ufw: rule=allow to_ip=any to_port={{item}} proto=any direction=in
  with_items:
    - 80
    - 443

- name: Add admin user to `www-data` group
  user: name={{admin_user}} groups=www-data append=true

- name: Give www-data write access to Apache directories
  file:
    path: "{{item}}"
    state: directory
    follow: false
    recurse: true
    group: www-data
    mode: g+wX
  with_items:
    - /etc/apache2
    - /var/www

- name: Enable Apache modules
  apache2_module:
    state: present
    name: "{{item}}"
  with_items:
    #- cgi
    - cgid
    - rewrite
    - ssl
  notify:
    - Restart Apache

- name: Disable other-vhosts-access-log
  command: a2disconf other-vhosts-access-log

- name: Add custom Apache configuration
  template:
    src: jwodder.conf
    dest: /etc/apache2/conf-available/jwodder.conf
    backup: true
  notify:
    - Restart Apache

- name: Enable custom Apache configuration
  command: a2enconf jwodder

- include: apache_access.yml
  when: "'logsdb' in features"

- name: Disable default website configuration
  command: a2dissite 000-default

- name: Configure custom default website
  template:
    src: domain.conf
    dest: /etc/apache2/sites-available/domain.conf
    backup: true
  notify:
    - Restart Apache

- name: Enable custom default website
  command: a2ensite domain

- name: Cut down on old Apache logs
  lineinfile:
    dest: /etc/logrotate.d/apache2
    line: "\t{{item.key}} {{item.value}}"
    regexp: '^\s*{{item.key}}'
    insertbefore: '^\s*\}$'
  with_dict:
    minsize: 512k
    rotate: 10

- name: Configure fail2ban
  copy:
    src: "fail2ban/{{item}}"
    dest: "/etc/fail2ban/{{item}}"
    backup: true
  with_items:
    - filter.d/apache-badbots.local
    - filter.d/apache-notaproxy.local
    - jail.d/apache.local
  notify:
    - Restart fail2ban
