---
- hosts: all
  become: true
  roles:
    - base  # `base` must be run before `admin` in order to configure /etc/skel
    - skel
    - admin

# Optional roles:
# - backup
# - dailyreport (requires mail and logsdb)
# - docker
# - loginmsg
# - logsdb (requires postgres)
# - mail (requires ssl)
# - postgres
# - ssl
# - xmission
