---
- hosts: all
  become: true
  roles:
    - base
    - skel
    - admin

# Optional roles:
# - backup
# - dailyreport (requires mail and logsdb)
# - devel
# - loginmsg
# - logsdb (requires postgres)
# - mail (requires ssl)
# - postgres
# - ssl
# - xmission
