---
mail_admin_aliases: []
mail_luser: muffins

mail_origin: varonathe.org  # Must be a domain name rather than a subdomain
mail_hostname: "mail.{{ mail_origin }}"  # Must be a subdomain of mail_origin
mail_destinations:
    - "{{ mail_origin }}"
    - "{{ mail_hostname }}"

certbot_cert_name: jwodder  # noqa: var-naming[no-role-prefix]

mail_spf_tools_version: 90b0c65d86ae21052c957361cb3895087f7651c6  # 2020-10-21
mail_postwhite_version: c880eb448959b831ea28c77a61c24c613b91db1d  # 2018-04-16
