---
- name: Configure SSHd to not show the "Last login" message
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#?PrintLastLog\s+'
    line: 'PrintLastLog no'
  notify:
    - Restart SSHd

- name: Configure PAM to show the "Last login" and "Failed logins" messages
  lineinfile:
    dest: /etc/pam.d/sshd
    # Insert between the pam_env lines and the pam_selinux line
    insertafter: 'pam_env'
    line: "{{item}}"
    backup: true
  with_items:
    # Note that the lines will & must appear in the opposite order in the
    # configured file.
    - 'session optional    pam_lastlog.so silent noupdate showfailed'
    - 'session [default=1] pam_lastlog.so nowtmp showfailed'

- name: Disable cruft in login message
  file:
    ### TODO: This will fail when the file doesn't exist; fix this!
    path: "/etc/update-motd.d/{{item}}"
    mode: 0644
  with_items:
    - '00-header'
    - '10-help-text'

- name: Omit Landscape link from sysinfo in login message
  replace:
    dest: /etc/update-motd.d/50-landscape-sysinfo
    regexp: 'landscape-sysinfo(?! --exclude-sysinfo-plugins)'
    replace: 'landscape-sysinfo --exclude-sysinfo-plugins=LandscapeLink'
    backup: true

- name: Disable live news
  lineinfile:
    dest: /etc/default/motd-news
    regexp: '^\s*#?\s*ENABLED='
    line: 'ENABLED=0'
