---
- name: Install vnstat
  ansible.builtin.apt:
    name: vnstat
    state: present
    update_cache: false

### TODO: Make vnstat only monitor eth0?

- name: Install bin/dailyreport
  ansible.builtin.copy:
    src: bin/dailyreport
    dest: "{{ jwodder_root }}/bin/dailyreport"
    owner: "{{ admin_user }}"
    mode: "0755"

- name: Create dailyreport cronjob
  ansible.builtin.cron:
    user: "{{ dailyreporter }}"
    name: dailyreport
    minute: 0
    hour: 8
    job: '{{ jwodder_root }}/bin/dailyreport | sendmail -t'
