---
- name: Install vnstat
  apt: name=vnstat state=present update_cache=no

### TODO: Make vnstat only monitor eth0?

- name: Install bin/dailyreport
  copy:
    src: bin/dailyreport
    dest: "{{jwodder_root}}/bin/dailyreport"
    mode: 0755

- name: Create dailyreport cronjob
  cron:
    user: "{{dailyreporter}}"
    name: dailyreport
    minute: 0
    hour: 8
    job: '{{jwodder_root}}/bin/dailyreport | sendmail -t'
