---
- name: Install prerequisites
  apt: name={{item}} state=present update_cache=no
  with_items:
    - python-pip
    - python-virtualenv

- name: Install Python Dropbox SDK
  pip:
    name: dropbox
    state: "{{update_dropbox|ternary('latest', 'present')}}"
    virtualenv: "{{dropbox_venv}}"

- name: Create backup cronjob
  copy:
    dest: /etc/cron.daily/backdroplet
    content: |
        #!/bin/bash
        # Run every other Sunday:
        (( ($(date +%s) / 86400 - 3) % 14 )) || \
            chronic /opt/jwodder/bin/backdroplet "{{dropbox_venv}}"
    mode: 0755
