---
- name: Install prerequisites
  apt: name={{item}} state=present update_cache=no
  with_items:
    - python-pip
    - python-virtualenv

- name: Install Python Dropbox SDK
  pip:
    name: dropbox
    state: "{{update_dropbox|ternary('latest', 'present')}}"
    virtualenv: "{{dropbox_venv}}"

- name: Install bin/backdroplet
  copy:
    src: bin/backdroplet
    dest: "{{jwodder_root}}/bin/backdroplet"
    mode: 0755

- name: Install bin/dropboxadd
  copy:
    src: bin/backdroplet
    dest: "{{jwodder_root}}/bin/dropboxadd"
    mode: 0755

- name: Install share/backup.exclude
  copy:
    src: share/backup.exclude
    dest: "{{jwodder_root}}/share/backup.exclude"

- name: Create backup cronjob
  copy:
    dest: /etc/cron.daily/backdroplet
    content: |
        #!/bin/bash
        # Run every other Sunday:
        (( ($(date +%s) / 86400 - 3) % 14 )) || \
            chronic {{jwodder_root|quote}}/bin/backdroplet {{dropbox_venv|quote}}
    mode: 0755
