---
- get_url:
    url: https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh
    dest: /usr/local/bin/dropbox_uploader
    mode: 0755
    force: "{{update_dropbox_uploader}}"

- name: Install bin/backdroplet
  copy:
    src: bin/backdroplet
    dest: "{{jwodder_root}}/bin/backdroplet"
    mode: 0755

- name: Install share/backup.exclude
  copy:
    src: share/backup.exclude
    dest: "{{jwodder_root}}/share/backup.exclude"

- name: Store Dropbox credentials
  copy:
    dest: "{{jwodder_root}}/etc/secret/dropbox_uploader"
    content: |
        OAUTH_ACCESS_TOKEN={{dropbox_oauth_access_token|quote}}
    mode: 0600
    owner: root
    group: root

- name: Create backup cronjob
  copy:
    dest: /etc/cron.daily/backdroplet
    content: |
        #!/bin/bash
        # Run every other Sunday:
        (( ($(date +%s) / 86400 - 3) % 14 )) || \
            chronic {{jwodder_root|quote}}/bin/backdroplet
    mode: 0755
