---
- name: Create jwodder
  user:
    name: jwodder
    groups: adm,staff,sudo,users  #,docker
    # `adm` membership lets me read files in `/var/log` without the need for
    # `sudo`.
    append: true
    shell: /bin/bash
    home: /home/jwodder
    move_home: true
    comment: 'John T. Wodder II'
    generate_ssh_key: true
    ssh_key_type: rsa
    ssh_key_comment: "jwodder@{{ansible_hostname}}"

- name: Fetch root's authorized_keys
  command: cat /root/.ssh/authorized_keys
  register: authkeys

- name: Add root's authorized_keys to jwodder's
  authorized_key: user=jwodder manage_dir=true key="{{authkeys.stdout}}"

- name: Set up Google Authenticator for jwodder
  shell: 'yes | google-authenticator'
  args:
    creates: /home/jwodder/.google_authenticator
  become_user: jwodder

- name: Give jwodder permission to run `sudo ufw` without a password
  lineinfile:
    dest: /etc/sudoers
    line: 'jwodder ALL=(ALL:ALL) NOPASSWD: /usr/sbin/ufw'
    validate: 'visudo -cf %s'

- name: Set crontab variables
  cronvar:
    user: jwodder
    name: "{{item.key}}"
    value: "{{item.value}}"
  with_dict:
    CONTENT_TYPE: 'text/plain; charset="utf-8"'
    CRONNING: 'true'
    LANG: en_US.UTF-8
    LC_ALL: en_US.UTF-8
    PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/jwodder/bin'

- name: Create cronjob for cleaning ~
  cron:
    user: jwodder
    name: purge
    minute: 0
    hour: 9
    job: 'cd ~; xargs -a /opt/jwodder/etc/cruft -r rm -rf'
