---
- name: Install Transmission
  apt: name={{item}} state=present update_cache=no
  with_items:
    - transmission-cli
    - transmission-daemon

- json_dict:
    dest: /etc/transmission-daemon/settings.json
    owner: debian-transmission
    group: debian-transmission
    mode: 0600
    backup: true
    update:
        download-queue-size: 10
        peer-port: 60069
        rpc-authentication-required: false
        rpc-bind-address: "127.0.0.1"
        script-torrent-done-enabled: true
        script-torrent-done-filename: "/opt/jwodder/bin/xmission-done"
        seed-queue-enabled: true
        speed-limit-down: 300
        speed-limit-down-enabled: true
        speed-limit-up: 300
        speed-limit-up-enabled: true
        trash-original-torrent-files: true
        watch-dir: "/home/debian-transmission/watch"
        watch-dir-enabled: false
  notify:
    - Reload Transmission

- name: Allow incoming connections to Transmission
  ### TODO: Does this need to allow both TCP and UDP?
  ufw: rule=allow to_ip=any to_port={{xmission_port}} proto=any direction=in

- name: Don't start Transmission automatically on system startup
  lineinfile:
    dest: /etc/init/transmission-daemon.override
    line: manual
    create: true
    owner: root
    group: root
