---
- name: Install bin/maillog
  ansible.builtin.copy:
    src: bin/maillog
    dest: "{{jwodder_root}}/bin/maillog"
    mode: 0755

- name: Install /etc/procmailrc
  ansible.builtin.template:
    src: etc.procmailrc
    dest: /etc/procmailrc
    backup: true

- name: Ensure maillog logfiles exist
  ansible.builtin.file:
    dest: "{{ jwodder_root }}/logs/{{ item }}"
    mode: "0666"
    state: touch
  with_items:
    - fatal.email
    - maillog.err
    - procmail.err
