---
# - name: Add DNS record for mail subdomain
#   ### TODO: Create a CNAME record instead when the mail_origin and
#   ### mail_hostname are the same server
#   set_do_dns_record:
#     oauth_token: "{{ digitalocean_token }}"
#     domain: "{{ mail_origin }}"
#     type: A
#     name: "{{ mail_hostname[:-(mail_origin | length)-1] }}"
#     data: "{{ ansible_default_ipv4.address }}"

# - name: Create DNS MX record
#   set_do_dns_record:
#     oauth_token: "{{ digitalocean_token }}"
#     domain: "{{ mail_origin }}"
#     type: MX
#     name: '@'
#     data: "{{ mail_hostname }}"

- name: Allow incoming SMTP connections
  community.general.ufw:
    rule: allow
    to_ip: any
    to_port: 25
    proto: any
    direction: in

- name: Configure postfix main_mailer_type
  ansible.builtin.debconf:
    name: postfix
    question: postfix/main_mailer_type
    vtype: select
    value: Internet Site

- name: Configure postfix mailname
  ansible.builtin.debconf:
    name: postfix
    question: postfix/mailname
    vtype: string
    value: "{{ mail_origin }}"

- name: Install postfix
  ansible.builtin.apt:
    name:
      - mailutils
      - opendkim
      - opendkim-tools
      - postfix
      - postgrey
      - procmail
    state: present
    update_cache: false

- name: Set up DKIM
  ansible.builtin.import_tasks: dkim.yml

- name: Set up postwhite
  ansible.builtin.import_tasks: postwhite.yml

- name: Create luser_relay user
  ansible.builtin.user:
    name: "{{ mail_luser }}"
    groups: mail
    append: true
    shell: /bin/bash
    home: "/home/{{ mail_luser }}"
    move_home: true
    comment: 'Mail Failure'

- name: Remove the contents of /etc/postgrey/whitelist_recipients
  ansible.builtin.copy:
    dest: /etc/postgrey/whitelist_recipients
    content: ''
    owner: root
    mode: "0644"
    backup: true

- name: Whitelist e-mails sent via Mailgun and Mandrill
  ansible.builtin.copy:
    dest: /etc/postgrey/whitelist_clients.local
    content: |
        mailgun.net
        mandrillapp.com
    owner: root
    mode: "0644"

- name: Configure Postfix
  ansible.builtin.template:
    src: main.cf
    dest: /etc/postfix/main.cf
    owner: root
    mode: "0644"
    backup: true
  notify:
    - Restart Postfix

- name: Configure /etc/aliases
  ansible.builtin.template:
    src: aliases
    dest: /etc/aliases
    owner: root
    mode: "0644"
    backup: true
  notify:
    - Run newaliases

- name: Populate /etc/postfix/access
  ansible.builtin.copy:
    src: access
    dest: /etc/postfix/access
    owner: root
    mode: "0644"
    backup: true
  notify:
    - Restart Postfix
    - Rehash access file

- name: Set up mail logging
  ansible.builtin.import_tasks: maillog.yml
  when: "'logsdb' in features"

- name: Install bin/mailuser  # used by mail_luser's procmailrc
  ansible.builtin.copy:
    src: bin/mailuser
    dest: "{{ jwodder_root }}/bin/mailuser"
    owner: "{{ admin_user }}"
    mode: "0755"

- name: Create procmailrc for luser
  ansible.builtin.template:
    src: luser.procmailrc
    dest: /home/{{ mail_luser }}/.procmailrc
    owner: "{{ mail_luser }}"
    group: "{{ mail_luser }}"
    mode: "0644"

- name: Configure admin user's mail
  ansible.builtin.import_tasks: admin.yml

- name: Create /var/mail.old
  ansible.builtin.file:
    path: /var/mail.old
    state: directory
    owner: mail
    group: mail
    mode: "0775"

- name: Configure logrotate to move old e-mails to /var/mail.old
  ansible.builtin.copy:
    src: mailboxes.logrotate
    dest: /etc/logrotate.d/mailboxes
    # The logrotate manpage doesn't mention that you need to chown root, but
    # it's very necessary.
    owner: root
    group: root
    mode: "0644"

- name: Create cronjob for deleting old e-mails
  ansible.builtin.copy:
    dest: /etc/cron.weekly/purge-mail
    content: |
        #!/bin/bash
        find /var/mail.old -type f -mtime +42 -delete
    owner: root
    mode: "0755"

- name: Configure fail2ban
  ansible.builtin.copy:
    src: postfix.local
    dest: /etc/fail2ban/jail.d/postfix.local
    owner: root
    mode: "0644"
    backup: true
  notify:
    - Restart fail2ban
