---
- name: Add DNS record for mail subdomain
  ### TODO: Create a CNAME record instead when the mail_origin and
  ### mail_hostname are the same server
  set_do_dns_record:
    oauth_token: "{{digitalocean_token}}"
    domain: "{{mail_origin}}"
    type: A
    name: "{{mail_hostname[:-(mail_origin|length)-1]}}"
    data: "{{ansible_default_ipv4.address}}"

- name: Create DNS MX record
  set_do_dns_record:
    oauth_token: "{{digitalocean_token}}"
    domain: "{{mail_origin}}"
    type: MX
    name: '@'
    data: "{{mail_hostname}}"

- name: Allow incoming SMTP connections
  ufw: rule=allow to_ip=any to_port=25 proto=any direction=in

- debconf:
    name: postfix
    question: postfix/main_mailer_type
    vtype: select
    value: Internet Site

- debconf:
    name: postfix
    question: postfix/mailname
    vtype: string
    value: "{{mail_origin}}"

- apt:
    name:
        - mailutils
        - opendkim
        - opendkim-tools
        - postfix
        - postgrey
        - procmail
    state: present
    update_cache: false

- include: dkim.yml
- include: postwhite.yml

- name: Create luser_relay user
  user:
    name: "{{luser}}"
    groups: mail
    append: true
    shell: /bin/bash
    home: "/home/{{luser}}"
    move_home: true
    comment: 'Mail Failure'

- name: Remove the contents of /etc/postgrey/whitelist_recipients
  copy:
    dest: /etc/postgrey/whitelist_recipients
    content: ''
    backup: true

- name: Whitelist e-mails sent via Mailgun and Mandrill
  copy:
    dest: /etc/postgrey/whitelist_clients.local
    content: |
        mailgun.net
        mandrillapp.com

- name: Configure Postfix
  template:
    src: main.cf
    dest: /etc/postfix/main.cf
    backup: true
  notify:
    - Restart Postfix

- name: Configure /etc/aliases
  template:
    src: aliases
    dest: /etc/aliases
    backup: true
  notify:
    - Run newaliases

- include: maillog.yml
  when: "'logsdb' in features"

- name: Install bin/mailuser  # used by luser's procmailrc
  copy:
    src: bin/mailuser
    dest: "{{jwodder_root}}/bin/mailuser"
    mode: 0755

- template:
    src: luser.procmailrc
    dest: /home/{{luser}}/.procmailrc
    owner: "{{luser}}"
    group: "{{luser}}"

- include: admin.yml

- name: Create /var/mail.old
  file:
    path: /var/mail.old
    state: directory
    owner: mail
    group: mail
    mode: 0775

- name: Configure logrotate to move old e-mails to /var/mail.old
  copy:
    src: mailboxes.logrotate
    dest: /etc/logrotate.d/mailboxes
    # The logrotate manpage doesn't mention that you need to chown root, but
    # it's very necessary.
    owner: root
    group: root

- name: Create cronjob for deleting old e-mails
  copy:
    dest: /etc/cron.weekly/purge-mail
    content: |
        #!/bin/bash
        find /var/mail.old -type f -mtime +42 -delete
    mode: 0755

- name: Configure fail2ban
  copy:
    src: postfix.local
    dest: /etc/fail2ban/jail.d/postfix.local
    backup: true
  notify:
    - Restart fail2ban
