---
- name: Install spf-tools
  ansible.builtin.git:
    repo: https://github.com/jsarenik/spf-tools
    dest: /usr/local/spf-tools
    update: false
  notify:
    - Run postwhite

- name: Install postwhite
  ansible.builtin.git:
    repo: https://github.com/stevejenkins/postwhite
    dest: /usr/local/postwhite
    update: false
  notify:
    - Run postwhite

- name: Install postwhite config file
  ansible.builtin.command: cp /usr/local/postwhite/postwhite.conf /etc/postwhite.conf
  args:
    creates: /etc/postwhite.conf

- name: Configure postwhite
  ansible.builtin.lineinfile:
    dest: /etc/postwhite.conf
    regexp: '^{{item.key}}='
    line: '{{item.key}}={{item.value}}'
  with_dict:
    spfttoolspath: /usr/local/spf-tools
    include_yahoo: 'no'
  notify:
    - Run postwhite

- name: Create postwhite cronjob
  ansible.builtin.copy:
    dest: /etc/cron.daily/postwhite
    content: |
        #!/bin/bash
        chronic /usr/local/postwhite/postwhite
    mode: 0755
