---
# Based on <https://repos-droplet.digitalocean.com/install.sh> (linked from
# <https://docs.digitalocean.com/products/droplets/how-to/manage-agent/>) as of
# 2026-05-24

- name: Download DigitalOcean droplet agent package key
  ansible.builtin.get_url:
    url: https://repos-droplet.digitalocean.com/gpg.key
    dest: /usr/share/keyrings/droplet-agent-keyring.gpg
    owner: root
    mode: "0644"
    force: false

- name: Create droplet-agent.list file
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/droplet-agent.list
    content: |
      deb [signed-by=/usr/share/keyrings/droplet-agent-keyring.gpg] https://repos-droplet.digitalocean.com/apt/droplet-agent main main
    owner: root
    mode: "0644"

- name: Create droplet-agent.pref file
  ansible.builtin.copy:
    dest: /etc/apt/preferences.d/droplet-agent.pref
    content: |
      Package: *
      Pin: origin repos-droplet.digitalocean.com
      Pin-Priority: 100
    owner: root
    mode: "0644"

- name: Install DigitalOcean droplet agent
  ansible.builtin.apt:
    name:
      - droplet-agent
      - droplet-agent-keyring
    state: present
    update_cache: true
