---
- name: Add Certbot PPA
  apt_repository: repo='ppa:certbot/certbot' update_cache=true

- name: Install Certbot
  apt:
    name: certbot
    state: "{{update_certbot|ternary('latest', 'present')}}"
