---
- assert: that='certbot_domains is defined and (certbot_domains|length > 0)'

- assert:
    that: 'certbot_source == "auto" or certbot_source == "ppa"'

- include: certbot_{{certbot_source}}.yml

- name: Install Certbot hooks
  copy:
    ### TODO: Use synchronize instead?
    src: "{{item}}"
    dest: "{{jwodder_root}}/{{item}}"
    mode: 0755
  with_items:
    - bin/certbot-post-hook
    - bin/certbot-pre-hook

- name: Get SSL certificates
  ### TODO: Is this idempotent?
  ### TODO: Force a run if certbot_domains changed?  Always run?
  command: |
    certbot certonly
        --standalone
        --rsa-key-size 4096
        --expand
        --email {{certbot_email|quote}}
        --domains {{certbot_domains|join(',')|quote}}
        --non-interactive
        --pre-hook {{jwodder_root|quote}}/bin/certbot-pre-hook
        --post-hook {{jwodder_root|quote}}/bin/certbot-post-hook
        --agree-tos
  args:
    creates: /etc/letsencrypt

- name: Create certificate renewal cronjob
  copy:
    dest: /etc/cron.weekly/certbot
    content: |
        #!/bin/bash
        chronic certbot renew \
            --quiet \
            --non-interactive \
            --pre-hook {{jwodder_root|quote}}/bin/certbot-pre-hook \
            --post-hook {{jwodder_root|quote}}/bin/certbot-post-hook
    mode: 0755
