---
- assert: that='certbot_domains is defined and (certbot_domains|length > 0)'

- name: Install Certbot
  apt:
    name:
        - certbot
        - python3-certbot-dns-digitalocean
    state: "{{update_certbot|ternary('latest', 'present')}}"

- name: Store DigitalOcean token
  template:
    dest: "{{jwodder_root}}/etc/secret/certbot_digitalocean.ini"
    src: certbot_digitalocean.ini
    mode: 0600
    owner: root
    group: root

- name: Create deploy hook folder
  file:
    path: /etc/letsencrypt/renewal-hooks/deploy
    state: directory
    owner: root
    group: root

- name: Install Certbot deploy hook
  copy:
    src: certbot-deploy-hook.sh
    dest: /etc/letsencrypt/renewal-hooks/deploy/certbot-deploy-hook
    mode: 0755

- name: Get SSL certificates
  ### Not idempotent
  ### TODO: Force a run if certbot_domains changed?  Always run?
  command: |
    certbot certonly
        --dns-digitalocean
        --dns-digitalocean-credentials {{jwodder_root|quote}}/etc/secret/certbot_digitalocean.ini
        --rsa-key-size 4096
        --expand
        --cert-name {{certbot_cert_name|quote}}
        --email {{certbot_email|quote}}
        --domains {{certbot_domains|join(',')|quote}}
        --non-interactive
        --agree-tos
  args:
    creates: /etc/letsencrypt/live/{{certbot_cert_name}}

# Cert autorenewal is done by a cronjob installed by the certbot package
