---
- assert: that='certbot_domains is defined and (certbot_domains|length > 0)'

- assert:
    that: 'certbot_source == "auto" or certbot_source == "ppa"'

- include: certbot_{{certbot_source}}.yml

- name: Create etc/certbot
  copy:
    dest: "{{jwodder_root}}/etc/certbot"
    content: |+
        DOMAINS={{certbot_domains|join(',')|quote}}
        EMAIL={{certbot_email|quote}}

- name: Install Certbot scripts
  copy:
    ### TODO: Use synchronize instead?
    src: "{{item}}"
    dest: "{{jwodder_root}}/{{item}}"
    mode: 0755
  with_items:
    - bin/certbot
    - bin/certbot-post-hook
    - bin/certbot-pre-hook
    - bin/certbot-renew

- name: Get SSL certificates
  command: "{{jwodder_root}}/bin/certbot"
  args:
    creates: /etc/letsencrypt
  ### TODO: Force a run if certbot_domains changed?  Always run?

- name: Create Certbot cronjob
  copy:
    dest: /etc/cron.weekly/certbot
    content: |
        #!/bin/bash
        chronic "{{jwodder_root|quote}}/bin/certbot-renew"
    mode: 0755
