---
- assert: that='certbot_domains is defined and (certbot_domains|length > 0)'

- name: Add Certbot PPA
  apt_repository: repo='ppa:certbot/certbot' update_cache=true

- name: Install Certbot
  apt:
    name: certbot
    state: "{{update_certbot|ternary('latest', 'present')}}"

- name: Install Certbot hooks
  copy:
    src: "{{item}}"
    dest: "{{jwodder_root}}/{{item}}"
    mode: 0755
  with_items:
    - bin/certbot-post-hook
    - bin/certbot-pre-hook

- name: Get SSL certificates
  ### TODO: Is this idempotent?
  ### TODO: Force a run if certbot_domains changed?  Always run?
  command: |
    certbot certonly
        --standalone
        --rsa-key-size 4096
        --expand
        --cert-name {{certbot_cert_name|quote}}
        --email {{certbot_email|quote}}
        --domains {{certbot_domains|join(',')|quote}}
        --non-interactive
        --pre-hook {{jwodder_root|quote}}/bin/certbot-pre-hook
        --post-hook {{jwodder_root|quote}}/bin/certbot-post-hook
        --agree-tos
  args:
    creates: /etc/letsencrypt/live/{{certbot_cert_name}}

# Cert autorenewal is done by a cronjob installed by the certbot package

#- name: Create certificate renewal cronjob
#  copy:
#    dest: /etc/cron.weekly/certbot
#    content: |
#        #!/bin/bash
#        chronic certbot renew \
#            --quiet \
#            --non-interactive \
#            --cert-name {{certbot_cert_name|quote}} \
#            --pre-hook {{jwodder_root|quote}}/bin/certbot-pre-hook \
#            --post-hook {{jwodder_root|quote}}/bin/certbot-post-hook
#    mode: 0755
