#!/bin/bash
FROM_ADDR='xmission@{{ mail_origin }}'
TO_ADDR='{{ xmission_recipient }}'

sendmail -t <<EOT
Subject: Download complete: $TR_TORRENT_NAME
From: $FROM_ADDR
To: $TO_ADDR

$TR_TORRENT_NAME
Torrent #$TR_TORRENT_ID ($TR_TORRENT_HASH)
Download dir: $TR_TORRENT_DIR

-- 
Transmission $TR_APP_VERSION
EOT
