#!/bin/bash
. "$JWODDER_ROOT/etc/certbot"

function installed {
    test "$(dpkg-query -Wf '${db:Status-Abbrev}' "$1" 2>/dev/null)" = "ii "
}

if installed apache2
then pre_hook="${pre_hook:+$pre_hook; }service apache2 stop"
     post_hook="${post_hook:+$post_hook; }service apache2 start"
else pre_hook="${pre_hook:+$pre_hook; }ufw allow in 80; ufw allow in 443"
     post_hook="${post_hook:+$post_hook; }ufw delete allow in 80; ufw delete allow in 443"
fi

if installed postfix
then post_hook="${post_hook:+$post_hook; }service postfix restart"
fi
