---
- name: Install Docker
  ansible.builtin.shell: |
    set -o pipefail
    wget -qO- https://get.docker.io | bash -
  args:
    creates: /usr/bin/docker

- name: Add admin user to `docker` group
  ansible.builtin.user:
    name: "{{ admin_user }}"
    groups: docker
    append: true
