---
# <https://github.com/cli/cli/blob/trunk/docs/install_linux.md#debian>

- name: Ensure /etc/apt/keyrings exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    mode: "0755"

- name: Download GitHub CLI package key
  ansible.builtin.get_url:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    dest: /etc/apt/keyrings/githubcli-archive-keyring.gpg
    owner: root
    mode: "0644"
    force: true

- name: Determine dpkg architecture
  ansible.builtin.command: dpkg --print-architecture
  changed_when: false
  register: base_arch

- name: Create github-cli.list file
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/github-cli.list
    content: |
      deb [arch={{ base_arch.stdout }} signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main
    owner: root
    mode: "0644"

- name: Install gh
  ansible.builtin.apt:
    name: gh
    state: present
    update_cache: true
