---
- name: Install PostgreSQL
  ansible.builtin.apt:
    name:
      - libpq-dev  # so psycopg2 can be installed via pip
      - postgresql
      - python3-psycopg2  # Needed by Ansible's postgresql_* modules
    state: present
    update_cache: false

# This makes the pager always use -S when doing `sudo -u postgres psql`:
- name: Configure psql pager for postgres user
  ansible.builtin.lineinfile:
    dest: ~postgres/.psqlrc
    regexp: '^\\setenv LESS\b'
    line: '\setenv LESS -iS'
    backup: true
    create: true
    owner: postgres
    mode: "0644"

# This lets me do `psql DATABASE` without needing `sudo` or an explicit login:
- name: Grant extra PostgreSQL powers to admin user
  community.postgresql.postgresql_user:
    name: "{{ admin_user }}"
    role_attr_flags: NOSUPERUSER,CREATEDB,CREATEROLE,LOGIN
  become: true
  become_user: postgres
