---
- name: Install PostgreSQL
  apt: name={{item}} state=present update_cache=no
  with_items:
    - postgresql
    - python-psycopg2
    - python3-psycopg2

# This makes the pager always use -S when doing `sudo -u postgres psql`:
- lineinfile:
    dest: ~postgres/.psqlrc
    regexp: '^\\setenv LESS\b'
    line: '\setenv LESS -iS'
    backup: true

# This lets me do `psql DATABASE` without needing `sudo` or an explicit login:
- postgresql_user:
    name: "{{admin_user}}"
    role_attr_flags: NOSUPERUSER,CREATEDB,CREATEROLE,LOGIN
  become_user: postgres
  when: admin_user is defined
