---
- name: Install Transmission
  apt: name={{item}} state=present update_cache=no
  with_items:
    - transmission-cli
    - transmission-daemon

- json_dict:
    dest: /etc/transmission-daemon/settings.json
    owner: debian-transmission
    group: debian-transmission
    mode: 0600
    backup: true
    update:
        download-queue-size: 10
        peer-port: "{{xmission_port}}"
        rpc-authentication-required: false
        rpc-bind-address: "127.0.0.1"
        rpc-host-whitelist-enabled: false
        script-torrent-done-enabled: true
        script-torrent-done-filename: "{{jwodder_root}}/bin/xmission-done"
        seed-queue-enabled: true
        speed-limit-down: 200
        speed-limit-down-enabled: true
        speed-limit-up: 200
        speed-limit-up-enabled: true
        trash-original-torrent-files: true
        watch-dir: "/var/lib/transmission-daemon/watch"
        watch-dir-enabled: true
  notify:
    - Reload Transmission

- name: Install xmission-done
  copy:
    src: bin/xmission-done
    dest: "{{jwodder_root}}/bin/xmission-done"
    mode: 0755

- name: Allow incoming connections to Transmission
  ### TODO: Does this need to allow both TCP and UDP?
  ufw: rule=allow to_ip=any to_port={{xmission_port}} proto=any direction=in

- name: Don't start Transmission automatically on system startup
  service: name=transmission-daemon enabled=false

- name: Create watch dir
  file:
    path: /var/lib/transmission-daemon/watch
    state: directory
    owner: debian-transmission
    group: debian-transmission
    mode: 0775

- name: Add admin user to `debian-transmission` group
  user: name={{admin_user}} groups=debian-transmission append=true
  when: admin_user is defined
