#!/bin/bash
# Run with sudo
# Prerequisite: apt-get install python-virtualenv
ROOT=/var/backups/jwodder
VENV=/var/lib/jwodder/dropbox

set -ex
mkdir -p "$ROOT"

for dir in /home/jwodder /var/mail /var/mail.old /var/www /etc/letsencrypt
do rsync -aR --copy-unsafe-links --delete --delete-excluded \
         --exclude-from=/etc/jwodder/backup.exclude \
         "$dir" "$ROOT"
done

sudo -u postgres pg_dump logs > "$ROOT/logs.sql"
#sudo -u postgres pg_dump tmpban > "$ROOT/tmpban.sql"

cd "$ROOT"
TARBALL=/var/backups/firefly-`date -u +%Y%m%dT%H%M%SZ`.tgz
tar zcf "$TARBALL" .

[ -e "$VENV" ] || virtualenv "$VENV"
source "$VENV/bin/activate"
pip install dropbox
python /usr/local/bin/dropboxadd "$TARBALL" /Historical/Backups/Droplets/

rm -f "$TARBALL"
