#!/bin/bash
# Run with sudo
# Prerequisite: apt-get install python-virtualenv
ROOT=/var/backups/jwodder
VENV=/var/lib/jwodder/dropbox

set -ex
mkdir -p "$ROOT"

for dir in /root /home /var/mail /var/mail.old /var/www /etc/letsencrypt /opt/jwodder
do if [ -e "$dir" ]
   then if [ "$dir" = /var/www ]
        then links=
        else links=--copy-unsafe-links
        fi
        rsync -aR $links --delete --delete-excluded \
              --exclude-from=/opt/jwodder/etc/backup.exclude \
              "$dir" "$ROOT"
   else rm -rf "$ROOT$dir"
   fi
done

if [ -x /etc/init.d/postgresql ]
### TODO: Look for a better way to test whether PostgreSQL is installed.
then sudo -u postgres pg_dumpall > "$ROOT/postgres.sql"
# Don't use `-f` here, as postgres can't write to $ROOT.
else rm -rf "$ROOT/postgres.sql"
fi

cd "$ROOT"
TARBALL=/var/backups/`hostname`-`date -u +%Y%m%dT%H%M%SZ`.tgz
tar zcf "$TARBALL" .

if [ ! -e "$VENV" ]
then virtualenv "$VENV"
     $VENV/bin/pip install dropbox
fi

$VENV/bin/python /opt/jwodder/bin/dropboxadd "$TARBALL" \
                                             /Historical/Backups/Droplets/

rm -f "$TARBALL"
