---
- name: Install development-related packages
  apt: name={{item}} state=present update_cache=no
  with_items:
    - build-essential
    - libncurses5-dev
    - libncursesw5-dev
    - ncurses-doc
    - patch
    - perl-doc
    - python-dev
    - python-pip
    - python-requests
    - python-six
    - python-virtualenv
    - python3-dev
    - python3-pip
    - python3-requests
    - python3-six

- name: Install Docker
  shell: 'wget -O- https://get.docker.io | bash -'
  args:
    creates: /usr/bin/docker

- name: Add admin user to `docker` group
  user: name={{admin_user}} groups=docker append=true
  when: admin_user is defined

- name: Install docker-compose
  pip:
    name: docker-compose
    state: "{{update_docker_compose|ternary('latest', 'present')}}"
    virtualenv: "{{docker_compose_venv}}"

- file:
    path: /usr/local/bin/docker-compose
    src: "{{docker_compose_venv}}/bin/docker-compose"
    state: link

- name: Check whether jq is installed
  get_bin_path: command=jq
  register: jq

- include: jq.yml
  when: jq.path is none
