---
- name: Install development-related packages
  apt: name={{item}} state=present update_cache=no
  with_items:
    - build-essential
    - libncurses5-dev
    - libncursesw5-dev
    - ncurses-doc
    - patch
    - perl-doc
    - python-dev
    - python-pip
    - python-requests
    - python-six
    - python-virtualenv
    - python3-dev
    - python3-pip
    - python3-requests
    - python3-six

- name: Install Docker
  shell: 'wget -O- https://get.docker.io | bash -'
  args:
    creates: /usr/bin/docker
