---
- set_fact:
    # This makes the variable accessible to subsequent roles, right?
    jwodder_root: "{{jwodder_root}}"

- name: Create jwodder package skeleton
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - "{{jwodder_root}}/bin"
    - "{{jwodder_root}}/etc"
    - "{{jwodder_root}}/lib"
    - "{{jwodder_root}}/share"
