---
- set_fact:
    # This makes the variable accessible to subsequent roles, right?
    jwodder_root: "{{jwodder_root}}"

- name: Create jwodder package skeleton
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - "{{jwodder_root}}/bin"
    - "{{jwodder_root}}/etc"
    - "{{jwodder_root}}/lib"
    - "{{jwodder_root}}/share"
    - "{{jwodder_root}}/venvs"

- name: Create secrets directory
  file:
    path: "{{jwodder_root}}/etc/secret"
    state: directory
    mode: 0700
    owner: root
    group: root

- name: Create logs directory
  file:
    path: "{{jwodder_root}}/logs"
    state: directory
    group: syslog
    mode: 0775
